env:
    token: "ENCRYPTED[c34c22f3e9bd9e32b2d65b7302b664bf7fc83abb1b88005adb1c9382cbc7fd36240d0cc4e7215e6ff062982359ebefc9]"
    chat_id: "ENCRYPTED[fc2e18302fad0c5037d9c32f8332519b30682501dc48797e045fe3bcbb5b60975689324d4221cc096f0f9ebeb95a7768]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: zenitsuxd/kernel:latest
      cpu: 8
      memory: 32G

  Build_Kernel_script:
      - git clone --depth=1 -b LA.UM.9.1.r1-08100-SMxxx0.0 https://github.com/tyuzu-xd/android_kernel_xiaomi_ginkgo-1 lv && cd lv
      - bash build-miui.sh --azure
 