env:
    token: "ENCRYPTED[15ba1eea40e46513083085f55cdca40b572955b309679a30978ad2f45652fe6b5c680f9cc8c5dbfd163a9eb10eefa57b]"
    chat_id: "ENCRYPTED[57cd2ad497c9857b15613057b07e874566ae5eba7a7b88c27826c488a4c98a5d47768318b6b43de454a62dba99921dbe]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: zenitsuxd/kernel:latest
      cpu: 8
      memory: 32G

  Build_Kernel_script:
      - git clone --depth=1 -b LA.UM.9.1.r1-08100-SMxxx0.0 https://github.com/tyuzu-xd/android_kernel_xiaomi_ginkgo-1 lv && cd lv
      - bash build-miui.sh --proton
 
