env:
    TG_TOKEN: "ENCRYPTED[ec5d016600994918b3b1eadf705d4ec5ae41ece4fa34f4ea717eff56c41bcc5a941fa072810fe0933b5aef5d3c473907]"
    TG_CHAT_ID: "ENCRYPTED[57cd2ad497c9857b15613057b07e874566ae5eba7a7b88c27826c488a4c98a5d47768318b6b43de454a62dba99921dbe]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: tyuzu/kernel:build
      cpu: 8
      memory: 32G

  Build_Kernel_script:
      - git clone --depth=1 -b MiuiQ https://github.com/tzuyu-xd/android_kernel_xiaomi_ginkgo lv && cd lv
      - bash build-clang.sh
      - bash build-gcc.sh
